# Generated by Django 4.0.3 on 2022-04-06 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('assunto', models.TextField(verbose_name='Assunto')),
                ('data', models.DateField(verbose_name='Data')),
                ('links', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Links extras')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeusProjetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('assunto', models.TextField(verbose_name='Assunto')),
                ('data', models.DateField(verbose_name='Data')),
                ('links', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Links extras')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ideias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('assunto', models.TextField(verbose_name='Assunto')),
                ('data', models.DateField(verbose_name='Data')),
                ('links', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Links extras')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conquistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('assunto', models.TextField(verbose_name='Assunto')),
                ('data', models.DateField(verbose_name='Data')),
                ('links', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Links extras')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('assunto', models.TextField(verbose_name='Assunto')),
                ('data', models.DateField(verbose_name='Data')),
                ('links', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Links extras')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
