# Generated by Django 4.0.3 on 2022-04-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='conquistas',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='ideias',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='meusprojetos',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='relatorios',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='atividades',
            name='assunto',
            field=models.CharField(max_length=300, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='atividades',
            name='links',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Link extra'),
        ),
        migrations.AlterField(
            model_name='conquistas',
            name='assunto',
            field=models.CharField(max_length=300, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='conquistas',
            name='links',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Link extra'),
        ),
        migrations.AlterField(
            model_name='ideias',
            name='assunto',
            field=models.CharField(max_length=300, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='ideias',
            name='links',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Link extra'),
        ),
        migrations.AlterField(
            model_name='meusprojetos',
            name='assunto',
            field=models.CharField(max_length=300, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='meusprojetos',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='meusprojetos',
            name='links',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='Link extra'),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='assunto',
            field=models.CharField(max_length=300, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='links',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Link extra'),
        ),
    ]
